defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: 
    consumer_secret:  

test:
  <<: *defaults
  twitter:
    consumer_key: 
    consumer_secret:  

production:
  <<: *defaults
