defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: 2irEnkhjcGG0n9pIQimHlw
    consumer_secret:  ymfIiexmVbOp7W8oiVdoOtGrSZ9S3cWjEeFhl4QSOe8

test:
  <<: *defaults
  twitter:
    consumer_key: 2irEnkhjcGG0n9pIQimHlw
    consumer_secret:  ymfIiexmVbOp7W8oiVdoOtGrSZ9S3cWjEeFhl4QSOe8

production:
  <<: *defaults